version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
       MYSQL_ROOT_PASSWORD: redolf
       MYSQL_DATABASE: products
       MYSQL_PASSWORD: redolf
       MYSQL_USER: redolf
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

# volumes:
#  application:
#     external: true

