server:
    port: 5000

spring:
   application:
       name: Kubernetes
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost:3307/${DB_DATABASE}
       password: ${DB_USER_PASSWORD}
       username: ${DB_USERNAME}
   jpa:
       hibernate:
           ddl-auto: update
       properties:
           hibernate:
               dialect: org.hibernate.dialect.MySQL8Dialect
               format_sql: true
               show_sql: true